# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VmrOfNtEmCcarGMc6w-cifiZBC5GL8Du
"""

import os

# Install xpdf-utils which contains the pdftext command
!apt-get update
!apt-get install -y xpdf-utils

from google.colab import drive
drive.mount('/content/drive')

import os

pasta = "/content/drive/MyDrive/Referencias_pdf"

files_in_directory = os.listdir(pasta)

for filename in files_in_directory:
    if filename.endswith(".pdf"):
        caminho_pdf = os.path.join(pasta, filename)

        print(f"Converting {filename} to text...")
        !pdftotext "{caminho_pdf}"
        print(f"Finished converting {filename}.")

import os

pasta = "/content/drive/MyDrive/REFERENCIAS_DATASET/Artigosseed_pdf_ate11"

files_in_directory = os.listdir(pasta)

for filename in files_in_directory:
    if filename.endswith(".pdf"):
        caminho_pdf = os.path.join(pasta, filename)

        print(f"Converting {filename}...")
        !pdftotext "{caminho_pdf}"
        print("OK")

import os
import shutil

# Pasta principal
pasta = "/content/drive/MyDrive/Referencias_coletadas"

# Pasta onde ficarão os arquivos TXT
pasta_txt = os.path.join(pasta, "Referencias_txt")

# Cria a pasta, caso ela não exista
os.makedirs(pasta_txt, exist_ok=True)

# Move todos os arquivos .txt para a nova pasta
for arquivo in os.listdir(pasta):
    if arquivo.endswith(".txt"):
        shutil.move(
            os.path.join(pasta, arquivo),
            os.path.join(pasta_txt, arquivo)
        )

print("Todos os arquivos .txt foram movidos para a pasta 'Referencias_txt'.")

import os
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import itertools

SEEDS_DIR      = "/content/drive/MyDrive/REFERENCIAS_DATASET/Artigosseed_txt"
CANDIDATOS_DIR = "/content/drive/MyDrive/REFERENCIAS_DATASET/Referencias_txt"

# ── Carregar documentos ───────────────────────────────────────────────────────
def load_texts(folder):
    docs = {}
    for fname in os.listdir(folder):
        if fname.endswith(".txt"):
            fpath = os.path.join(folder, fname)
            with open(fpath, "r", encoding="utf-8", errors="ignore") as f:
                docs[fname] = f.read()
    return docs

seeds      = load_texts(SEEDS_DIR)
candidatos = load_texts(CANDIDATOS_DIR)

print(f"Seeds carregados: {len(seeds)}")
print(f"Candidatos carregados: {len(candidatos)}")

# ── TF-IDF + Similaridade ─────────────────────────────────────────────────────
candidato_ids   = list(candidatos.keys())
candidato_texts = list(candidatos.values())

vectorizer = TfidfVectorizer(stop_words=None)
candidatos_matrix = vectorizer.fit_transform(candidato_texts)

print("\n" + "=" * 60)
print("SIMILARIDADE TF-IDF — Seeds vs Candidatos")
print("=" * 60)

for seed_nome, seed_text in seeds.items():
    seed_vec = vectorizer.transform([seed_text])
    similarities = cosine_similarity(seed_vec, candidatos_matrix)[0]

    ranked_indices = np.argsort(similarities)[::-1]

    print(f"\nSeed: {seed_nome}")
    print("  Top 10 mais similares:")
    for i, idx in enumerate(ranked_indices[:10]):
        print(f"    {i+1}. {candidato_ids[idx]} — similaridade: {similarities[idx]:.4f}")

# Install the rank_bm25 library
!pip install rank_bm25

import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

from rank_bm25 import BM25Okapi
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import numpy as np
import pandas as pd
import os # Added for file operations

# Download necessary NLTK data (if not already downloaded)
try:
    nltk.data.find('corpora/stopwords')
except nltk.downloader.DownloadError:
    nltk.download('stopwords')
try:
    nltk.data.find('tokenizers/punkt')
except nltk.downloader.DownloadError:
    nltk.download('punkt')

# --- BEGIN: Code copied from TF-IDF cell (aYiMbld2ghDd) to define 'seeds', 'candidatos', 'candidato_ids' ---
SEEDS_DIR      = "/content/drive/MyDrive/REFERENCIAS_DATASET/Artigosseed_txt"       # os 32 artigos em .txt, mas so tem 11
CANDIDATOS_DIR = "/content/drive/MyDrive/REFERENCIAS_DATASET/Referencias_txt"  # artigos das referências em .txt

# Carregar documentos
def load_texts(folder):
    docs = {}
    for fname in os.listdir(folder):
        if fname.endswith(".txt"):
            fpath = os.path.join(folder, fname)
            with open(fpath, "r", encoding="utf-8", errors="ignore") as f:
                docs[fname] = f.read()
    return docs

seeds      = load_texts(SEEDS_DIR)
candidatos = load_texts(CANDIDATOS_DIR)

candidato_ids   = list(candidatos.keys())
# candidato_texts = list(candidatos.values()) # This is defined later, only the keys are needed here for candidato_ids
# --- END: Code copied ---

stop_words = set(stopwords.words('portuguese')) # Assuming Portuguese stop words

def tokenize_text(text):
    words = word_tokenize(text.lower(), language='portuguese')
    return [word for word in words if word.isalnum() and word not in stop_words]

# Tokenize candidate documents for BM25
tokenized_candidatos = [tokenize_text(text) for text in candidatos.values()]

# Initialize BM25Okapi model
bm25 = BM25Okapi(tokenized_candidatos)

print("\n" + "=" * 60)
print("BM25 Ranking — Seeds vs Candidatos")
print("=" * 60)

# Prepare to store results
bm25_rankings = []

# Define snippet length
snippet_length = 200

# Perform BM25 ranking for each seed
for seed_nome, seed_text in seeds.items():
    tokenized_query = tokenize_text(seed_text)
    doc_scores = bm25.get_scores(tokenized_query)

    # Get the indices of the top-ranking documents
    # Ensure we handle cases where there are fewer than 10 candidates
    ranked_indices = np.argsort(doc_scores)[::-1]

    # Extract seed document snippet
    seed_snippet = seed_text[:snippet_length] + '...' if len(seed_text) > snippet_length else seed_text

    # Collect only the top 10 ranked documents for this seed for storage
    for rank, idx in enumerate(ranked_indices[:10]): # Modified here to take only top 10
        candidate_document_name = candidato_ids[idx]
        candidate_full_text = candidatos[candidate_document_name]
        candidate_snippet = candidate_full_text[:snippet_length] + '...' if len(candidate_full_text) > snippet_length else candidate_full_text

        bm25_rankings.append({
            'seed_document': seed_nome,
            'seed_snippet': seed_snippet,
            'candidate_document': candidate_document_name,
            'candidate_snippet': candidate_snippet,
            'bm25_score': doc_scores[idx],
            'rank': rank + 1
        })

    print(f"\nSeed: {seed_nome}")
    print("  Top 10 mais similares (BM25):")
    for i, idx in enumerate(ranked_indices[:10]):
        print(f"    {i+1}. {candidato_ids[idx]} — Score: {doc_scores[idx]:.4f}")

# Convert to DataFrame
bm25_rankings_df = pd.DataFrame(bm25_rankings)
display(bm25_rankings_df.head())

# Save to CSV
output_filename = 'bm25_rankings.csv'
bm25_rankings_df.to_csv(output_filename, index=False)
print(f"\nBM25 rankings saved to {output_filename}")

import os
import pandas as pd

PASTA = "/content/drive/MyDrive/REFERENCIAS_DATASET/Referencias_txt"

dados = []

for arquivo in os.listdir(PASTA):
    if arquivo.endswith(".txt"):
        caminho = os.path.join(PASTA, arquivo)

        with open(caminho, "r", encoding="utf-8", errors="ignore") as f:
            texto = f.read()

        n_palavras = len(texto.split())

        dados.append({
            "arquivo": arquivo,
            "palavras": n_palavras
        })

df = pd.DataFrame(dados)

# Ordena do maior para o menor
df = df.sort_values("palavras", ascending=False)

display(df)

print("\nResumo:")
print(df["palavras"].describe())